models:
  - name: "HuggingFaceFW/ablation-model-c4" 
    revision: "step-001000-2BT"
    cls: "hf"
    batch_size: 100
    device: "cuda"
    architecture: "llama"
    dataset: "C4"
    dataset_version: "v1"
    dataset_size: "300B"

  - name: "HuggingFaceFW/ablation-model-c4" 
    revision: "step-005000-10BT"
    cls: "hf"
    batch_size: 100
    device: "cuda"
    architecture: "llama"
    dataset: "C4"
    dataset_version: "v1"
    dataset_size: "300B"

  - name: "HuggingFaceFW/ablation-model-c4" 
    revision: "step-010000-21BT"
    cls: "hf"
    batch_size: 100
    device: "cuda"
    architecture: "llama"
    dataset: "C4"
    dataset_version: "v1"
    dataset_size: "300B"

  - name: "HuggingFaceFW/ablation-model-c4" 
    revision: "step-015000-31BT"
    cls: "hf"
    batch_size: 100
    device: "cuda"
    architecture: "llama"
    dataset: "C4"
    dataset_version: "v1"
    dataset_size: "300B"

  - name: "HuggingFaceFW/ablation-model-c4" 
    revision: "step-020000-42BT"
    cls: "hf"
    batch_size: 100
    device: "cuda"
    architecture: "llama"
    dataset: "C4"
    dataset_version: "v1"
    dataset_size: "300B"

  - name: "HuggingFaceFW/ablation-model-c4" 
    revision: "step-025000-52BT"
    cls: "hf"
    batch_size: 100
    device: "cuda"
    architecture: "llama"
    dataset: "C4"
    dataset_version: "v1"
    dataset_size: "300B"

  - name: "HuggingFaceFW/ablation-model-c4" 
    revision: "step-030000-63BT"
    cls: "hf"
    batch_size: 100
    device: "cuda"
    architecture: "llama"
    dataset: "C4"
    dataset_version: "v1"
    dataset_size: "300B"

  - name: "HuggingFaceFW/ablation-model-c4" 
    revision: "step-035000-73BT"
    cls: "hf"
    batch_size: 100
    device: "cuda"
    architecture: "llama"
    dataset: "C4"
    dataset_version: "v1"
    dataset_size: "300B"

  - name: "HuggingFaceFW/ablation-model-c4" 
    revision: "step-040000-84BT"
    cls: "hf"
    batch_size: 100
    device: "cuda"
    architecture: "llama"
    dataset: "C4"
    dataset_version: "v1"
    dataset_size: "300B"

  - name: "HuggingFaceFW/ablation-model-c4" 
    revision: "step-045000-94BT"
    cls: "hf"
    batch_size: 100
    device: "cuda"
    architecture: "llama"
    dataset: "C4"
    dataset_version: "v1"
    dataset_size: "300B"

  - name: "HuggingFaceFW/ablation-model-c4" 
    revision: "step-050000-105BT"
    cls: "hf"
    batch_size: 100
    device: "cuda"
    architecture: "llama"
    dataset: "C4"
    dataset_version: "v1"
    dataset_size: "300B"

  - name: "HuggingFaceFW/ablation-model-c4" 
    revision: "step-055000-115BT"
    cls: "hf"
    batch_size: 100
    device: "cuda"
    architecture: "llama"
    dataset: "C4"
    dataset_version: "v1"
    dataset_size: "300B"

  - name: "HuggingFaceFW/ablation-model-c4" 
    revision: "step-060000-126BT"
    cls: "hf"
    batch_size: 100
    device: "cuda"
    architecture: "llama"
    dataset: "C4"
    dataset_version: "v1"
    dataset_size: "300B"

  - name: "HuggingFaceFW/ablation-model-c4" 
    revision: "step-065000-136BT"
    cls: "hf"
    batch_size: 100
    device: "cuda"
    architecture: "llama"
    dataset: "C4"
    dataset_version: "v1"
    dataset_size: "300B"

  - name: "HuggingFaceFW/ablation-model-c4" 
    revision: "step-070000-147BT"
    cls: "hf"
    batch_size: 100
    device: "cuda"
    architecture: "llama"
    dataset: "C4"
    dataset_version: "v1"
    dataset_size: "300B"

  - name: "HuggingFaceFW/ablation-model-c4" 
    revision: "step-075000-157BT"
    cls: "hf"
    batch_size: 100
    device: "cuda"
    architecture: "llama"
    dataset: "C4"
    dataset_version: "v1"
    dataset_size: "300B"

  - name: "HuggingFaceFW/ablation-model-c4" 
    revision: "step-080000-168BT"
    cls: "hf"
    batch_size: 100
    device: "cuda"
    architecture: "llama"
    dataset: "C4"
    dataset_version: "v1"
    dataset_size: "300B"

  - name: "HuggingFaceFW/ablation-model-c4" 
    revision: "step-085000-178BT"
    cls: "hf"
    batch_size: 100
    device: "cuda"
    architecture: "llama"
    dataset: "C4"
    dataset_version: "v1"
    dataset_size: "300B"

  - name: "HuggingFaceFW/ablation-model-c4" 
    revision: "step-090000-189BT"
    cls: "hf"
    batch_size: 100
    device: "cuda"
    architecture: "llama"
    dataset: "C4"
    dataset_version: "v1"
    dataset_size: "300B"

  - name: "HuggingFaceFW/ablation-model-c4" 
    revision: "step-095000-199BT"
    cls: "hf"
    batch_size: 100
    device: "cuda"
    architecture: "llama"
    dataset: "C4"
    dataset_version: "v1"
    dataset_size: "300B"

  - name: "HuggingFaceFW/ablation-model-c4" 
    revision: "step-100000-210BT"
    cls: "hf"
    batch_size: 100
    device: "cuda"
    architecture: "llama"
    dataset: "C4"
    dataset_version: "v1"
    dataset_size: "300B"

  - name: "HuggingFaceFW/ablation-model-c4" 
    revision: "step-105000-220BT"
    cls: "hf"
    batch_size: 100
    device: "cuda"
    architecture: "llama"
    dataset: "C4"
    dataset_version: "v1"
    dataset_size: "300B"

  - name: "HuggingFaceFW/ablation-model-c4" 
    revision: "step-130000-273BT"
    cls: "hf"
    batch_size: 100
    device: "cuda"
    architecture: "llama"
    dataset: "C4"
    dataset_version: "v1"
    dataset_size: "300B"

  - name: "HuggingFaceFW/ablation-model-c4" 
    revision: "step-135000-283BT"
    cls: "hf"
    batch_size: 100
    device: "cuda"
    architecture: "llama"
    dataset: "C4"
    dataset_version: "v1"
    dataset_size: "300B"

  - name: "HuggingFaceFW/ablation-model-c4" 
    revision: "step-140000-294BT"
    cls: "hf"
    batch_size: 100
    device: "cuda"
    architecture: "llama"
    dataset: "C4"
    dataset_version: "v1"
    dataset_size: "300B"

  - name: "HuggingFaceFW/ablation-model-c4" 
    revision: "step-145000-304BT"
    cls: "hf"
    batch_size: 100
    device: "cuda"
    architecture: "llama"
    dataset: "C4"
    dataset_version: "v1"
    dataset_size: "300B"

  - name: "HuggingFaceFW/ablation-model-c4" 
    cls: "hf"
    batch_size: 100
    device: "cuda"
    architecture: "llama"
    dataset: "C4"
    dataset_version: "v1"
    dataset_size: "300B"