models:
  # RedPajama v1 (800B tokens) Models
  ## GPT Architecture
  - name: "togethercomputer/RedPajama-INCITE-7B-Base"
    cls: "hf" # lm_eval argument
    batch_size: 8
    device: "cuda"
    architecture: "GPT"
    dataset: "RedPajama"
    dataset_version: "v1"
    dataset_size: "1T tokens"

  - name: "togethercomputer/RedPajama-INCITE-Base-3B-v1"
    cls: "hf" # lm_eval argument
    batch_size: 4
    device: "cuda"
    architecture: "GPT"
    dataset: "RedPajama"
    dataset_version: "v1"
    dataset_size: "800B tokens"