models:
  # Refined Web (180B tokens) Models
    ## Falcon Architecture
  - name: "tiiuae/falcon-rw-1b"
    cls: "hf" # lm_eval argument
    batch_size: 8
    device: "cuda"
    architecture: "Falcon"
    dataset: "Refined Web"
    dataset_version: "v1"
    dataset_size: "350B tokens"

  - name: "tiiuae/falcon-rw-7b"
    cls: "hf" # lm_eval argument
    batch_size: 4
    device: "cuda"
    architecture: "Falcon"
    dataset: "Refined Web"
    dataset_version: "v1"
    dataset_size: "350B tokens"